"""build_cdd_pdf.py

Bundle all the Critical Difference Diagrams (CDDs) of one SLIM version into a
single PDF, reproducing the paper's Fig. 3 (per-individual CDDs: BF/BS/OC x
Test RMSE/Size) and Fig. 4 (the ALL-vs-BASE final-model CDDs).

The per-diagram .tex fragments are produced by reproduce_plots.py into
cdd_plots/. This script wraps them in a standalone LaTeX document and compiles
it to PDF with `tectonic`.

Usage (from the project root):
    python slim_gsgp/build_cdd_pdf.py            # uses VERSION_TAG below
Edit VERSION_TAG to pick the version (must match the *_cdd_<TAG>.tex files).
"""
import os
import subprocess
import sys

# ---------------------------------------------------------------------------
# Which version's CDDs to bundle. Must match the suffix on the .tex files
# generated by reproduce_plots.py (e.g. "N1", "N2", "ABS").
# ---------------------------------------------------------------------------
VERSION_TAG = "N1"

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))          # slim_gsgp/
CDD_DIR = os.path.join(_THIS_DIR, "reproduced_plots", "cdd_plots")

# Fig. 3 — per-individual CDDs, in a 3x2 grid (rows: BF, BS, OC).
FIG3 = [
    ("best_fitness/fitness_cdd",      "BF: Test RMSE"),
    ("best_fitness/size_cdd",         "BF: Size"),
    ("best_size/fitness_cdd",         "BS: Test RMSE"),
    ("best_size/size_cdd",            "BS: Size"),
    ("optimal_compromise/fitness_cdd","OC: Test RMSE"),
    ("optimal_compromise/size_cdd",   "OC: Size"),
]
# Fig. 4 — final-model CDDs (ALL vs BASE), 1x2.
FIG4 = [
    ("ALL_fitness_cdd", "Test RMSE"),
    ("ALL_size_cdd",    "Size"),
]


def _frag(rel):
    """Path of a CDD fragment for the current tag, relative to CDD_DIR."""
    return f"{rel}_{VERSION_TAG}.tex"


def _check_exist():
    missing = []
    for rel, _ in FIG3 + FIG4:
        if not os.path.exists(os.path.join(CDD_DIR, _frag(rel))):
            missing.append(_frag(rel))
    return missing


def _subfigure(rel, sub_caption):
    # \resizebox scales the whole diagram (axis + the treatment labels that
    # stick out beyond it) down to the subfigure width, so it never overflows.
    return (
        "\\begin{subfigure}{0.48\\textwidth}\n"
        "\\centering\n"
        f"\\resizebox{{\\linewidth}}{{!}}{{\\input{{{_frag(rel)}}}}}\n"
        f"\\caption{{{sub_caption}}}\n"
        "\\end{subfigure}"
    )


def build_tex():
    version_label = "SLIM+" + VERSION_TAG  # for the captions

    cap3 = (
        "\\caption{Critical difference diagrams for the Best Fitness (BF), "
        "Optimal Compromise (OC) and Best Size (BS) models; where A.: ALL and "
        "B.: BASE. (" + version_label + ")}"
    )
    cap4 = (
        "\\caption{Critical Difference Diagram comparing the final models "
        "(BF, BS and OC) found by the ALL variant with the SLIM (BASE) BF "
        "model. (" + version_label + ")}"
    )

    lines = [
        r"\documentclass[11pt]{article}",
        r"\usepackage[margin=1.2cm]{geometry}",
        r"\usepackage{graphicx}",
        r"\usepackage{tikz}",
        r"\usepackage{pgfplots}",
        r"\pgfplotsset{compat=1.18}",
        r"\usepackage{subcaption}",
        r"\usepackage{amsmath}",
        r"\pagestyle{empty}",
        r"\begin{document}",
        r"",
        r"\begin{figure}[t]",
        r"\centering",
    ]
    # Fig 3: 3 rows x 2 cols
    for i in range(0, len(FIG3), 2):
        left = _subfigure(*FIG3[i])
        right = _subfigure(*FIG3[i + 1])
        lines.append(left + "\n\\hfill\n" + right)
        if i + 2 < len(FIG3):
            lines.append(r"\vspace{1.5em}")
    lines += [
        cap3,
        r"\end{figure}",
        r"",
        r"\begin{figure}[t]",
        r"\centering",
        _subfigure(*FIG4[0]) + "\n\\hfill\n" + _subfigure(*FIG4[1]),
        cap4,
        r"\end{figure}",
        r"",
        r"\end{document}",
    ]
    return "\n".join(lines)


def main():
    missing = _check_exist()
    if missing:
        print("ERROR: missing CDD fragments for tag "
              f"'{VERSION_TAG}':")
        for m in missing:
            print(f"  - reproduced_plots/cdd_plots/{m}")
        print("Run reproduce_plots.py with the matching SLIM_VERSION first.")
        return 1

    tex = build_tex()
    tex_path = os.path.join(CDD_DIR, f"all_cdds_{VERSION_TAG}.tex")
    with open(tex_path, "w") as fp:
        fp.write(tex)
    print(f"Wrote wrapper: {tex_path}")

    # Compile with tectonic (resolves \input relative to the .tex directory).
    try:
        proc = subprocess.run(
            ["tectonic", tex_path],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        print("ERROR: 'tectonic' not found on PATH. Install it (brew install "
              "tectonic) or compile the wrapper .tex with your LaTeX engine.")
        return 1

    pdf_path = os.path.join(CDD_DIR, f"all_cdds_{VERSION_TAG}.pdf")
    if proc.returncode != 0 or not os.path.exists(pdf_path):
        print("ERROR: tectonic failed to compile. Output:")
        print(proc.stdout[-2000:])
        print(proc.stderr[-2000:])
        return 1

    print(f"Saved PDF: {pdf_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
